version: '3.8'

services:
  family-ai-assistant:
    build: .
    container_name: family-ai-assistant
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    restart: unless-stopped 